blog/blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

from posts.urls import views
from accounts.views import login_view, logout_view, register_view

urlpatterns = [
    url(r'^$', views.post_list),
    url(r'^comments/', include('comments.urls', namespace='comments')),
    url(r'^api/posts/', include('posts.api.urls', namespace="posts-api")),
    url(r'^api/comments/', include('comments.api.urls', namespace="comments-api")),
    url(r'^posts/', include('posts.urls', namespace="posts")),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^register/', register_view, name='register'),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/posts/api/urls.py
from django.conf.urls import url

from .views import (PostListAPIView,
                    PostRetrieveAPIView,
                    PostUpdateAPIView,
                    PostDestroyAPIView,
                    PostCreateAPIView)

urlpatterns = [
    url(r'^$', PostListAPIView.as_view(), name='list'),
    url(r'^create$', PostCreateAPIView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', PostRetrieveAPIView.as_view(), name='detail'),
    url(r'^edit/(?P<pk>\d+)/$', PostUpdateAPIView.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)/$', PostDestroyAPIView.as_view(), name='delete'),
]

blog/posts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='list'),
    url(r'^create$', views.post_create, name='create'),
    url(r'^(?P<slug>\w+)/$', views.post_detail, name='detail'),
    url(r'^edit/(?P<slug>\w+)/$', views.post_edit, name='edit'),
    url(r'^delete/(?P<slug>\w+)/$', views.post_delete, name='delete'),
]

blog/posts/models.py
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from markdown_deux import markdown

from comments.models import Comment
from .utils import get_read_time


class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super().filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    return "{!s}/{!s}".format(instance.id, filename)


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location,
                              null=True, blank=True,
                              width_field='width_field',
                              height_field='height_field')
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    read_time = models.IntegerField(default=0)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField('date published', auto_now=False, auto_now_add=True)

    objects = PostManager()  # filter hook

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-updated', '-timestamp']

    @property
    def absolute_url(self):
        return reverse('posts:detail', args=(self.id,))

    @property
    def markdown(self):
        return mark_safe(markdown(self.content))

    @property
    def comments(self):
        return Comment.objects.filter_by_instance(self)

    @property
    def content_type(self):
        return ContentType.objects.get_for_model(self.__class__)


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    posts = Post.objects.filter(slug=slug).order_by('-id')
    if posts.exists():
        new_slug = "{!s}-{!s}".format(slug, posts.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.markdown:
        instance.read_time = get_read_time(instance.markdown)

pre_save.connect(pre_save_post_receiver, sender=Post)

blog/posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from .models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)

    class Meta:
        model = Post
        fields = ['title', 'content', 'image',
                  'draft', 'publish']

blog/posts/api/views.py
from django.db.models import Q

from rest_framework.filters import (
    SearchFilter,
    OrderingFilter
)

from rest_framework.generics import (
    ListAPIView,
    RetrieveAPIView,
    RetrieveUpdateAPIView,
    DestroyAPIView,
    CreateAPIView)


from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly
)

from .pagination import PostLimitOffsetPagination, PostPageNumberPagination
from .permissions import IsOwnerOrReadOnly

from ..models import Post
from .serializers import (PostListSerializer,
                          PostDetailSerializer,
                          PostCreateSerializer)


class PostCreateAPIView(CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateSerializer
    permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class PostListAPIView(ListAPIView):
    serializer_class = PostListSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['title', 'content', 'user__first_name']
    pagination_class = PostPageNumberPagination

    def get_queryset(self, *args, **kwargs):
        posts = Post.objects.all()
        query = self.request.GET.get('q')
        if query:
            posts = posts.filter(
                Q(title__icontains=query) |
                Q(content__icontains=query) |
                Q(user__first_name__icontains=query) |
                Q(user__last_name__icontains=query)
            ).distinct()
        return posts


class PostRetrieveAPIView(RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer


class PostUpdateAPIView(RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    permission_classes = [IsAuthenticatedOrReadOnly,
                          IsAdminUser,
                          IsOwnerOrReadOnly]

    def perform_update(self, serializer):
        serializer.save(user=self.request.user)


class PostDestroyAPIView(DestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    permission_classes = [IsAuthenticated,
                          IsAdminUser,
                          IsOwnerOrReadOnly]

blog/posts/views.py
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from comments.forms import CommentForm
from comments.models import Comment
from .models import Post
from .forms import PostForm


def post_create(request):
    if not request.user.is_authenticated():
        messages.success(request, 'User is not logged in.')
        return redirect('posts:list')
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, 'Post created successfully.')
        return redirect('posts:list')

    context = {
        'form': form,
    }
    return render(request, 'posts/post_form.html', context=context)


def post_detail(request, slug):
    post = get_object_or_404(Post, pk=slug)

    if post.draft or post.publish > timezone.now().date():
        user = request.user
        if not user.is_staff or not user.is_superuser:
            raise Http404

    initial_data = {
        'content_type': post.content_type,
        'object_id': post.id,
    }
    comment_form = CommentForm(request.POST or None, initial=initial_data)

    if comment_form.is_valid():

        # Users must be logged in to comment
        if not request.user.is_authenticated():
            messages.success(request, 'User is not logged in.')
            return HttpResponseRedirect(reverse('posts:detail', args=(post.id,)))

        parent_obj = None
        c_type = comment_form.cleaned_data.get('content_type')
        try:
            parent_id = int(request.POST.get('parent_id'))
        except TypeError:
            parent_id = None

        # Store the parent id if we are processing a reply
        # Confirm that the parent comment exists in the DB
        if parent_id:
            queryset = Comment.objects.filter(id=parent_id)
            if queryset.exists():
                parent_obj = queryset.first()

        Comment.objects.get_or_create(
            user=request.user,
            content_type=ContentType.objects.get(model=c_type),
            object_id=comment_form.cleaned_data.get('object_id'),
            content=comment_form.cleaned_data.get('content'),
            parent=parent_obj,
        )

        return HttpResponseRedirect(reverse('posts:detail', args=(post.id,)))

    context = {
        'post': post,
        'comment_form': comment_form,
    }
    return render(request, 'posts/detail.html', context)


def post_list(request):
    today = timezone.now().date()
    posts = Post.objects.active()

    # Staff can see everything
    user = request.user
    if user.is_staff or user.is_superuser:
        posts = Post.objects.all()

    query = request.GET.get('q')
    if query:
        posts = posts.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query)
        ).distinct()

    paginator = Paginator(posts, 6)  # Show 6 contacts per page
    page = request.GET.get('page')
    try:
        posts_per_page = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts_per_page = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts_per_page = paginator.page(paginator.num_pages)

    context = {
        'posts': posts_per_page,
        'today': today,
    }
    return render(request, 'posts/post_list.html', context)


def post_edit(request, slug):
    if not request.user.is_authenticated():
        messages.success(request, 'User is not logged in.')
        return redirect('posts:list')
    post = get_object_or_404(Post, pk=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=post)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, 'Post updated.')
        return HttpResponseRedirect(reverse('posts:detail', args=(post.id,)))

    context = {
        'post': post,
        'form': form,
    }

    return render(request, 'posts/post_form.html', context=context)


def post_delete(request, slug):
    if not request.user.is_authenticated():
        messages.success(request, 'User is not logged in.')
        return redirect('posts:list')
    post = get_object_or_404(Post, pk=slug)
    post.delete()
    messages.success(request, 'Post deleted successfully.')
    return redirect('posts:list')

blog/posts/templates/posts/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<head>
    <title>{% block title %}Try Django 1.9{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'posts/css/style.css' %}">

    <style>
        {% block style %}{% endblock %}
    </style>

{% block head_extra %}{% endblock %}
</head>
<body>
<div class="container">
    <ol class="breadcrumb">
        <li><a href="{% url 'posts:list' %}">Home</a></li>
        {% block post_detail_link %}
        {% endblock %}

        {% if not request.user.is_authenticated %}
            <li class="pull-right"><a href="{% url 'register' %}">Register</a></li>
            <li class="pull-right"><a href="{% url 'login' %}">Login</a></li>
        {% else %}
            <li class="pull-right"><a href="{% url 'logout'%}">Logout</a></li>
        {% endif %}
    </ol>
<div id="fb-root"></div>

<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.6&appId=1568773046695203";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

{% include 'posts/messages.html' %}

{% block content %}
{% endblock %}
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js"></script>

<script src="{% static 'posts/js/post.js' %}"></script>
</body>
</html>

blog/posts/templates/posts/detail.html
{% extends 'posts/base.html' %}
{% load crispy_forms_tags %}
{% load urlify %}
{% block title %}{{ post.title }}{% endblock %}

{% block post_detail_link %}
    <li><a href="{{ post.absolute_url }}">{{ post.title }}</a></li>
{% endblock %}

{% block content %}

<div class="col-sm-8 col-sm-offset-3">
    <h1>{{ post.title}}{%if post.draft %}&nbsp;
        <small><span style="color: red;">(draft)</span></small>{% endif %}</h1>
    <span class="post-detail-item">{{ post.markdown }}</span><br>
    {% if post.image %}
        <img src="{{ post.image.url }}" class="img-responsive">
    {% endif %}
    <br>
        {% if post.user.get_full_name %}
            <strong>Author: {{ post.user.get_full_name }}</strong> <br>
                {% else %}
            <strong>Author: {{post.user|capfirst}}</strong> <br>
        {% endif %}
        <p>Originally posted: {{post.publish}}<br>
        Last edited: {{post.updated|timesince}} ago</p>
    <div class="fb-like"></div>
    <hr>
    <p><a href="{% url 'posts:edit' post.id %}" class="btn btn-primary" role="button">Edit</a>
       <a href="{% url 'posts:delete' post.id %}" class="btn btn-primary" role="button">Delete</a>
       <a href="{% url 'posts:list' %}" class="btn btn-default" role="button">Back</a>
    </p>
    <br>
    <div>
        <p class="lead">Comments</p>
        {% if request.user.is_authenticated %}
        <form action="." method="post">
            {{ comment_form|crispy }}
            <button type="submit" class="btn btn-default">Post Comment</button>
            {% csrf_token %}
        </form>
        {% else %}
            <p>You must login to comment</p>
        {% endif %}
        <hr>
        {% for comment in post.comments %}
            <blockquote>
                {{ comment.content }}
                <footer>via {{comment.user }} | {{ comment.timestamp|timesince }} ago
                {% if comment.children.count > 0 %}
                    | {{ comment.children.count }}
                    repl{{comment.children.count|pluralize:'y,ies'}}
                {% endif %}
                    | <a class="comment-reply-btn" href="#"> Reply </a>
                    | <a class="" href="{{ comment.absolute_url}}"> Thread </a>
                </footer>
                <div class="comment-reply">
                    <hr>
                    {% for reply in comment.children %}
                    <blockquote>
                        {{ reply.content }}
                        <footer>via {{ reply.user }} | {{ reply.timestamp|timesince }} ago</footer>
                    </blockquote>
                    {% endfor %}

                    {% if request.user.is_authenticated %}
                    <form action="." method="post">
                        {{ comment_form|crispy }}
                        <input type="hidden" name="parent_id" value="{{ comment.id }}">
                        <button type="submit" class="btn btn-default">Reply</button>
                        {% csrf_token %}
                    </form>
                    {% else %}
                        <p>You must login to comment</p>
                    {% endif %}
                </div>
            </blockquote>
            <hr>
        {% endfor %}
    </div>
</div>

{% endblock %}

blog/posts/templates/posts/messages.html
<div class="messages">
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>

blog/posts/templates/posts/post_form.html
{% extends 'posts/base.html' %}
{% load crispy_forms_tags %}

{% block head_extra %}
    {{ form.media }}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <h1>Preview</h1>
        <hr>
        <div class="content-preview">
            <h3 id="preview-title"></h3>
            <p id="preview-content"></p>
        </div>
    </div>
    <div class="col-md-6">
        <h1>Form</h1>
        <hr>
        <form action="" method="post" enctype="multipart/form-data">
            {{ form|crispy }}
            <button type="submit" class="btn btn-default">Create Post</button>
            {% csrf_token %}
        </form>
    </div>
</div>

{% endblock %}

blog/posts/templates/posts/post_list.html
{% extends 'posts/base.html' %}
{% block content %}

<div class="col-sm-12">
    <h1>Post List</h1>
    <form action="" method="GET" class="row">
        <div class="col-sm-8">
            <div class="input-group">
                <input class="form-control" type="text" name="q"
                       value="{{ request.GET.q }}" placeholder="Search posts">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button" >
                        <span style="color: green;" class="glyphicon glyphicon-search"></span></button>
                </span>
            </div>
        </div>
    </form>
    <br>
    <div class="row">
        {% for post in posts %}
        <div class="col-sm-12">
            <div class="thumbnail">
                {% if post.image %}
                <img src="{{ post.image.url }}" class="img-responsive">
                {% endif %}
                <div class="caption">
                    <a href="{% url 'posts:detail' post.id %}">
                        <h1>{{ post.title }}</h1></a>

                    <small>
                        {% if post.user.get_full_name %}
                        by {{ post.user.get_full_name }} on
                        {% endif %}
                        {% if post.publish > today %}
                            <span style="color: green; font-weight: bold;">*{{ post.publish }}*</span>
                        {% else %}
                            {{ post.publish }}
                        {% endif %}
                    </small>
                    {% if post.draft %}
                        <span style="color: red; font-weight: bold;"> Draft</span>
                    {% endif %}
                    <p><strong>Read Time:</strong>
                        < {{ post.read_time }} minute{{post.read_time|pluralize}}
                    </p>
                    <span class="post-detail-item">{{ post.markdown|truncatewords_html:12 }}</span><br>
                    <p><a href="{% url 'posts:detail' post.id %}" class="btn btn-primary" role="button">View</a></p>
                </div>
            </div>
        </div>

        {% endfor %}

        <a href="{% url 'posts:create' %}" class="btn btn-default" role="button">New Post</a>
        <hr>
        <div class="pagination">
        <span class="step-links">
            {% if posts.has_previous %}
                <a href="?page={{ posts.previous_page_number }}
                {% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}
            </span>

            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}
                {% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
            {% endif %}
        </span>
        </div>
    </div>
</div>

{% endblock content %}